<!-- Product Detail -->
<div class="container bgwhite p-t-35 p-b-80">
	<div class="flex-w flex-sb">
		<div class="w-size13 p-t-30 respon5">
	        <div class="wrap-slick3 flex-sb flex-w">
			    <?php if($this->floors){ ?>
	        	<div class="wrap-slick3-dots"></div>				
				<div class="slick3">
		            <?php foreach ($this->floors  as $floor => $seats): ?>
			        	<div class="item-slick3" data-thumb="<?php echo $this->getAssetsURL();?>/images/thumb-item-<?php echo $floor?>.jpg">
			        		<div class="workspace">
			        	    	<?php for($x=1; $x<=25; $x++){ ?>
			        	    	    <?php for($y=1; $y<=20; $y++){ ?>
			        	    	        <div class="seat-space 
			        	    			            <?php echo ($x == 25) ? "seat-last-row": ""; ?>
			        	    						<?php echo ($y == 20) ? "seat-last-col": ""; ?>" 
			        	    			     id="<?php echo $floor."_".$x."_".$y;?>">
			        	    			</div>
			        	    	    <?php } ?>
			        	    		<br />
			        	    	<?php } ?>
			        	    </div>
			            </div>
			        <?php endforeach ?>
		        </div>
				<?php } else { ?>
				    <div class="workspace">
					    <?php for($x=1; $x<=25; $x++){ ?>
			        	    <?php for($y=1; $y<=20; $y++){ ?>
			        	        <div class="seat-space 
			        			            <?php echo ($x == 25) ? "seat-last-row": ""; ?>
			        						<?php echo ($y == 20) ? "seat-last-col": ""; ?>">
			        			</div>
			        	    <?php } ?>
			        		<br />
			        	<?php } ?>
					</div>
				<?php } ?>
	        </div>
			<?php if (isset($this->lastModified)){ ?>
			<div style="width:100%;">
			    <div class="flex-w t-center p-t-25 m-l-r-auto" style="width:80%;">
                    <div class="s-text21 m-l-r-auto pos-relative seat-vacant" style="width:30%; height:25px;">Vacant</div>
                    <div class="s-text21 m-l-r-auto pos-relative seat-occupied" style="width:30%; height:25px;">Occupied</div>
                    <div class="s-text21 m-l-r-auto pos-relative seat-unavailable" style="width:30%; height:25px;">Unavailable</div>
			        <span class="s-text8 m-l-r-auto p-t-15">Last modified: <?php echo $this->lastModified; ?></span>
			    </div>
			</div>
			<?php }?>
		</div>
		<div class="w-size14 p-t-30 respon5">
		    <div class="dis-inline-block">
		        <div class="w-size20 float-l">
			        <h4 class="product-detail-name m-text16 p-b-13"><?php echo $this->restaurant['restaurant_name']; ?></h4>
			        <p class="s-text8 p-t-10"><?php echo $this->restaurant['branch_name']; ?></p>
			        <p class="s-text8 p-t-10"><?php echo $this->restaurant['short_desc']; ?></p>
			    </div>
			    <div class="w-size19 float-l">
			    	<div class="block2-img wrap-pic-w of-hidden pos-relative">
			    	    <img src="<?php echo $this->getAssetsURL().'/images/restaurants/'.$this->restaurant['image']; ?>" alt="IMG-PRODUCT">
			    		<div class="block2-overlay trans-0-4"></div>
			    	</div>
                </div>
			</div>
			<div class="wrap-dropdown-content bo6 p-t-15 p-b-14 active-dropdown-content">
				<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
					Description
					<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
					<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
				</h5>
				<div class="dropdown-content dis-none p-t-15 p-b-23">
					<p class="s-text8"><?php echo $this->restaurant['full_desc']; ?></p>
				</div>
			</div>
			<div class="wrap-dropdown-content bo7 p-t-15 p-b-14">
				<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
					Additional information
					<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
					<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
				</h5>
				<div class="dropdown-content dis-none p-t-15 p-b-23">
					<p class="s-text8">Address: <?php echo $this->restaurant['address']; ?></p>
					<p class="s-text8">Business Hours: <?php echo $this->restaurant['business_hours']; ?></p>
				</div>
			</div>
			<div class="wrap-dropdown-content bo7 p-t-15 p-b-14">
				<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
					Contact Information
					<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
					<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
				</h5>
				<div class="dropdown-content dis-none p-t-15 p-b-23">
					<p class="s-text8">Website: <?php echo $this->restaurant['website']; ?></p>
					<p class="s-text8">Phone number : <?php echo $this->restaurant['full_desc']; ?></p>
				</div>
			</div>
		</div>
	</div>
</div>
<style>
    .slick-track {
    	width: 500px;
    	height: 600px;
    }
</style>
<script type="text/javascript">
$(document).ready(function () {
	/* Set seat status */
    var floors = <?php echo json_encode($this->floors); ?>;
	$.each(floors, function(floor_id, floor){
		$.each(floor, function(index, seat){
			var seat_id = floor_id+"_"+seat["row_no"]+"_"+seat["col_no"];
			$("#"+seat_id).addClass("seat-assign seat-"+seat["seat_status_name"]);
		});
	});
});
</script>