<!-- breadcrumb -->
<div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
	<a href="index.html" class="s-text16">Home
		<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
	</a>
	<a href="product.html" class="s-text16">Women
		<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
	</a>
	<a href="#" class="s-text16">T-Shirt
		<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
	</a>
	<span class="s-text17">Restaurant Name</span>
</div>
<!-- Product Detail -->
<div class="container bgwhite p-t-35 p-b-80">
	<div class="flex-w flex-sb">
		<div class="w-size13 p-t-30 respon5">
			<div class="wrap-slick3 flex-sb flex-w">
				<div class="wrap-slick3-dots"></div>
				<div class="slick3">
					<div class="item-slick3" data-thumb="assets/images/thumb-item-01.jpg">
						<div class="wrap-pic-w">
							<img src="assets/images/product-detail-01.jpg" alt="IMG-PRODUCT">
						</div>
					</div>
					<div class="item-slick3" data-thumb="assets/images/thumb-item-02.jpg">
						<div class="wrap-pic-w">
							<img src="assets/images/product-detail-02.jpg" alt="IMG-PRODUCT">
						</div>
					</div>
					<div class="item-slick3" data-thumb="assets/images/thumb-item-03.jpg">
						<div class="wrap-pic-w">
							<img src="assets/images/product-detail-03.jpg" alt="IMG-PRODUCT">
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="w-size14 p-t-30 respon5">
			<h4 class="product-detail-name m-text16 p-b-13">Restaurant Name</h4>
			<p class="s-text8 p-t-10">
				Short description.... Lalalalala lalalala lalalalala.. lorem lorem lorem lorem lorem loremmmm.
			</p>
			<div class="p-b-45">
				<span class="s-text8 m-r-35">SKU: MUG-01</span>
				<span class="s-text8">Categories: Mug, Design</span>
			</div>
			<div class="wrap-dropdown-content bo6 p-t-15 p-b-14 active-dropdown-content">
				<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
					Description
					<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
					<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
				</h5>
				<div class="dropdown-content dis-none p-t-15 p-b-23">
					<p class="s-text8">
						Long description. Fusce ornare mi vel risus porttitor dignissim. Nunc eget risus at ipsum blandit ornare vel sed velit. Proin gravida arcu nisl, a dignissim mauris placerat
					</p>
				</div>
			</div>
			<div class="wrap-dropdown-content bo7 p-t-15 p-b-14">
				<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
					Additional information
					<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
					<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
				</h5>
				<div class="dropdown-content dis-none p-t-15 p-b-23">
					<p class="s-text8">Address: Manila</p>
					<p class="s-text8">Business Hours: 10:00~17:00</p>
				</div>
			</div>
			<div class="wrap-dropdown-content bo7 p-t-15 p-b-14">
				<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
					Contact Information
					<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
					<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
				</h5>
				<div class="dropdown-content dis-none p-t-15 p-b-23">
					<p class="s-text8">Email Address: abc@gmail.com</p>
					<p class="s-text8">Phone number : 012-0000-1234</p>
				</div>
			</div>
		</div>
	</div>
</div>