<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div class="page-title-icon"><i class="pe-7s-car icon-gradient bg-mean-fruit"></i></div>
            <div>Restaurant Profile
                <div class="page-title-subheading">Tell us about your restaurant.</div>
            </div>
        </div>
	</div>
</div>
<div class="main-card mb-3 card">
    <div class="card-body"><h5 class="card-title">Restaurant Information</h5>
        <form action="" method="post" id="form-profile" enctype="multipart/form-data" class="needs-validation" novalidate>
            <div class="form-row">
            	<!-- Basic Info -->
	            <div class="col-md-6">
				    <div class="form-row">
				        <div class="col-md-6 mb-2">
		                    <label for="name">Restaurant Name *</label>
		                    <input type="text" id="name" name="name" class="mb-2 form-control" value="<?php echo $this->restaurant['restaurant_name']; ?>"  maxlength="50" required />
							<div class="invalid-feedback">Please provide a restaurant name.</div>
		                </div>
				        <div class="col-md-6 mb-2">
					        <label for="branch">Branch Name</label>
				            <input type="text" id="branch" name="branch" class="mb-2 form-control" value="<?php echo $this->restaurant['branch_name']; ?>" maxlength="50" />
		                </div>
					</div>
					<div class="form-row">
					    <div class="col-md-6 mb-2 form-group">
					        <label for="website">Website</label>
				            <input type="text" id="website" name="website" class="mb-2 form-control" value="<?php echo $this->restaurant['website']; ?>" maxlength="50" />
					    </div>
					    <div class="col-md-6 mb-2 form-group">
					        <label for="phoneno">Phone Number</label>
				            <input type="text" id="phoneno" name="phoneno" class="mb-2 form-control" value="<?php echo $this->restaurant['phone_no']; ?>" maxlength="20" />
					    </div>
					</div>
					<div class="form-row">
						<div class="col-md-6 mb-2 form-group">
					        <label for="hours">Business Hours</label>
				            <input type="text" id="hours" name="hours" class="mb-2 form-control" value="<?php echo $this->restaurant['business_hours']; ?>" maxlength="30" />
					    </div>
					    <div class="col-md-6 mb-2 form-group">
					        <label for="image">Restaurant Photo</label>
				            <input type="file" name="image" id="image" class="form-control-file">
							<input type="hidden" id="oldImage" name="oldImage" value="<?php echo $this->restaurant['image']; ?>" />
					    </div>
					</div>
					<div class="position-relative form-group">
					    <label for="shortDesc">Short Description</label>
				        <textarea id="shortDesc" name="shortDesc" class="form-control" maxlength="500"><?php echo $this->restaurant['short_desc']; ?></textarea>
					</div>
					<div class="position-relative form-group">
					    <label for="fullDesc">Full Description</label>
				        <textarea id="fullDesc" name="fullDesc" class="form-control" maxlength="500"><?php echo $this->restaurant['full_desc']; ?></textarea>
					</div>
	            </div>
	            <!-- Map -->
	            <div class="col-md-6">
	            	<label for="address">Address</label>
	            	<input type="hidden" id="address" name="address" value="<?php echo $this->restaurant['address']; ?>" />
	            	<input type="hidden" id="longitude" name="longitude" value="<?php echo $this->restaurant['longitude']; ?>" />
	            	<input type="hidden" id="latitude" name="latitude" value="<?php echo $this->restaurant['latitude']; ?>" />
				    <div id="map"></div>
	            </div>
				<div class="m-t-20 m-l-r-auto">
					<button class="mb-2 mr-2 btn btn-dark" type="button" id="cancel">Cancel</button>
					<button class="mb-2 btn btn-dark">Submit</button>
				</div>
	        </div>
        </form>
    </div>
</div>
<!-- Save data -->
<script type="text/javascript">
$(document).ready(function () {
	/* Cancel changes */
	$("#cancel").on("click", function(){
		swal({
			title: "Are you sure?",
			text: "Your changes will be lost when you continue this action.",
			icon: "warning",
			buttons: true
		})
		.then((yes) => {
			if (yes) {
				location.href = "<?php echo $this->getBaseURL()?>profile";
			}
		});
	});
	/* Update profile information */
    $("#form-profile").submit(function(e){
		e.preventDefault();
		swal({
			title: "Are you sure?",
			text: "This change will be applied to your account once submitted.",
			icon: "warning",
			buttons: true
		})
		.then((yes) => {
			if (yes){
				var form = document.getElementById("form-profile");
				if (form.checkValidity() != false){
					$.ajax({
						url: "<?php echo $this->getControllerURL('profile', 'update')?>",
						type: 'POST',
						data: new FormData(this),
						processData: false,
						contentType: false,
						success:
							function(data){
							   swal("Success!", "You have successfully updated your restaurant profile.", "success");
							}
					});
				}else {
					e.preventDefault();
					e.stopPropagation();
				}
				form.classList.add('was-validated');
			}
		});
    });
});
</script>
<!-- Mapbox Geocoding -->
<script src="https://api.mapbox.com/mapbox-gl-js/v1.9.1/mapbox-gl.js"></script>
<link href="https://api.mapbox.com/mapbox-gl-js/v1.9.1/mapbox-gl.css" rel="stylesheet" />
<style>
	body { margin: 0; padding: 0; }
	#map { max-width: 100%; max-height: 100%; width: 616px; height: 500px;}
</style>
<script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.4.2/mapbox-gl-geocoder.min.js"></script>
<link
rel="stylesheet"
href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.4.2/mapbox-gl-geocoder.css"
type="text/css"
/>
<!-- Promise polyfill script required to use Mapbox GL Geocoder in IE 11 -->
<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>
<script>
	mapboxgl.accessToken = 'pk.eyJ1IjoiZ2xhZHlzYnJvY2UiLCJhIjoiY2s4dm12a3d3MGpjNjNqbzd1NDVnN3NkeCJ9.6MLAKKbn0ssuw6JtUT9DKA';
	var lng = "<?php echo ($this->restaurant['longitude']);?>";
	var lat = "<?php echo ($this->restaurant['latitude']);?>";
	// Default: Manila
	if (lng == ""){lng = 121.000000;}
	if (lat == ""){lat = 14.583330;}
	var map = new mapboxgl.Map({
		container: 'map',
		style: 'mapbox://styles/mapbox/streets-v11',
		center: [lng, lat],
		zoom: 13
	});
	var geocoder = new MapboxGeocoder({
			accessToken: mapboxgl.accessToken,
			mapboxgl: mapboxgl
		});
	map.addControl(geocoder);
	geocoder.on('result', function(data) {
		$("#address").attr("value", data["result"]["place_name"]);
		$("#longitude").attr("value", data["result"]["center"][0]);
		$("#latitude").attr("value", data["result"]["center"][1]);
	});
</script>