<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div class="page-title-icon"><i class="pe-7s-car icon-gradient bg-mean-fruit"></i></div>
            <div>User Account
                <div class="page-title-subheading">Update your user information.</div>
            </div>
        </div>
	</div>
</div>
<div class="main-card card col-md-4">
    <div class="card-body"><h5 class="card-title">Change Password</h5>
        <form action="" id="form-user" enctype="multipart/form-data" class="needs-validation" novalidate>
			<div class="position-relative form-group">
			    <div class="mb-2">
		            <label for="current">Current Password *</label>
		            <input type="password" id="current" name="current" class="mb-2 form-control"  minlength="8" maxlength="100" required>
					<div class="invalid-feedback">Please enter your current password.</div>
		        </div>
			</div>
			<div class="position-relative form-group">
			    <div class="mb-2">
		            <label for="new">New Password *</label>
		            <input type="password" id="new" name="new" class="mb-2 form-control"  minlength="8" maxlength="100" required>
					<div class="invalid-feedback">Please enter your new password.</div>
		        </div>
			</div>
			<div class="position-relative form-group">
			    <div class="mb-2">
		            <label for="confirm">Confirm New Password *</label>
		            <input type="password" id="confirm" name="confirm" class="mb-2 form-control"  minlength="8" maxlength="100" required>
					<div class="invalid-feedback">Please confirm your new password.</div>
		        </div>
			</div>
			<div class="m-t-20 t-center">
				<button class="mb-2 mr-2 btn btn-dark" type="button" id="cancel">Cancel</button>
				<button class="mb-2 btn btn-dark">Submit</button>
			</div>
        </form>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function () {
	$("#cancel").on("click", function(){
		swal({
			title: "Are you sure?",
			text: "Your changes will be lost when you continue this action.",
			icon: "warning",
			buttons: true
		})
		.then((yes) => {
			if (yes) {
				location.href = "<?php echo $this->getBaseURL()?>user";
			}
		});
	});
    $("#form-user").submit(function(e){
		e.preventDefault();
		swal({
			title: "Are you sure?",
			text: "Do you really want change your password?",
			icon: "warning",
			buttons: true,
			dangerMode: true
		})
		.then((yes) => {
			if (yes){
				var form = document.getElementById("form-user");
				if (form.checkValidity() != false){

						$.ajax({
							url: "<?php echo $this->getControllerURL('user', 'update')?>",
							type: 'POST',
							data: $(this).serialize(),
							success:
								function(result){
								   switch(result){
										case "0":
											swal("Great!", "You have successfully updated your password.", "success");
											break;
										case "1":
											swal("Update Failed", "The current password you provided is incorrect.", "error");
											break;
										case "2":
											swal("Update Failed", "The new password you entered did not match.", "error");
											break;
										case "3":
											swal("Update Failed", "A problem occured while updating the password.", "error");
											break;
										default: break;
									}
								}
						});
					
				}else {
					e.preventDefault();
					e.stopPropagation();
				}
				form.classList.add('was-validated');
			}
		});
    });
});
</script>