<div id="tbl-1" class="table-responsive">
    <table class="mb-0 table">
        <thead>
        <tr>
            <th>No.</th>
            <th>Date</th>
            <th>No. of Customers</th>
        </tr>
        </thead>
        <tbody>
		<?php foreach ($this->customerLogs  as $key=>$val): ?>
        <tr>
            <th scope="row"><?php echo $key+1; ?></th>
            <td><?php echo $val["date"]; ?></td>
            <td><?php echo $val["count"]; ?></td>
        </tr>
		<?php endforeach ?>
        </tbody>
    </table>
    <button class="mb-2 mr-2 btn btn-focus btn-csv" id="btn-csv-1">Export CSV</button>
	<button class="mb-2 mr-2 btn btn-focus btn-pdf" id="btn-pdf-1">Generate PDF</button>
</div>