<div id="customerTbl" class="table-responsive">
    <table class="mb-0 table">
        <thead>
        <tr>
            <th>No.</th>
            <th>Date</th>
            <th>No. of Customers</th>
        </tr>
        </thead>
        <tbody>
		<?php foreach ($this->customerLogs  as $key=>$val): ?>
        <tr>
            <th scope="row"><?php echo $key+1; ?></th>
            <td><?php echo $val["date"]; ?></td>
            <td><?php echo $val["count"]; ?></td>
        </tr>
		<?php endforeach ?>
        </tbody>
    </table>
</div>