<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div class="page-title-icon">
                <i class="pe-7s-car icon-gradient bg-mean-fruit">
                </i>
            </div>
            <div>Reports
                <div class="page-title-subheading">View the number of costumers in your restaurant each day as well as the most frequently used seats.
                </div>
            </div>
        </div>
	</div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="main-card mb-3 card">
            <div class="card-body">
			    <h5 class="card-title">Customers</h5>
				<div class="dropdown d-inline-block w-full p-b-10">
					<div class="float-l t-center" style="width:15%;"><span id="date-label">FROM</span></div>
					<input type="text" id="start-date-1" class="date form-control float-l" autocomplete="off" style="width:38%;"/>
					<div class="float-l t-center" style="width:9%;"><span id="date-label">TO</span></div>
					<input type="text" id="end-date-1" class="date form-control float-l" autocomplete="off" style="width:38%;"/>
                </div>
                <div id="tbl-1" class="table-responsive">
                    <table class="mb-0 table">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Date</th>
                            <th>No. of Customers</th>
                        </tr>
                        </thead>
                        <tbody>
						<?php foreach ($this->customerLogs  as $key=>$val): ?>
                        <tr>
                            <th scope="row"><?php echo $key+1; ?></th>
                            <td><?php echo $val["date"]; ?></td>
                            <td><?php echo $val["count"]; ?></td>
                        </tr>
						<?php endforeach ?>
                        </tbody>
                    </table>
					<div class="m-t-20 t-center">
						<button class="mb-2 mr-2 btn btn-dark btn-csv" id="btn-csv-1">Export CSV</button>
						<button class="mb-2 btn btn-dark btn-pdf" id="btn-pdf-1">Generate PDF</button>
					</div>
                </div>
            </div>
        </div>
    </div>
	<div class="col-lg-6">
        <div class="main-card mb-3 card">
            <div class="card-body">
			    <h5 class="card-title">Top Seats</h5>
				<div class="dropdown d-inline-block w-full p-b-10">
					<div class="float-l t-center" style="width:15%;"><span id="date-label">FROM</span></div>
					<input type="text" id="start-date-2" class="date form-control float-l" autocomplete="off" style="width:38%;"/>
					<div class="float-l t-center" style="width:9%;"><span id="date-label">TO</span></div>
					<input type="text" id="end-date-2" class="date form-control float-l" autocomplete="off" style="width:38%;"/>
                </div>
                <div id="tbl-2" class="table-responsive">
                    <table class="mb-0 table">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Row</th>
							<th>Column</th>
                            <th>No. of Customers</th>
                        </tr>
                        </thead>
						<?php foreach ($this->seatLogs  as $key=>$val): ?>
                        <tr>
                            <th scope="row"><?php echo $key+1; ?></th>
                            <td><?php echo $val["row_no"]; ?></td>
                            <td><?php echo $val["col_no"]; ?></td>
							<td><?php echo $val["count"]; ?></td>
                        </tr>
						<?php endforeach ?>
                        </tbody>
                    </table>
					<div class="m-t-20 t-center">
						<button class="mb-2 mr-2 btn btn-dark btn-csv" id="btn-csv-2">Export CSV</button>
						<button class="mb-2 btn btn-dark btn-pdf" id="btn-pdf-2">Generate PDF</button>
					</div>
                </div>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
$(document).ready(function () {
    $("body").on("click", ".btn-csv", function(){
		var elem = $(this).attr("id");
		var tbl = elem[elem.length - 1];			
		var start = $("#start-date-"+tbl).val();
		var end   = $("#end-date-"+tbl).val();
		window.open('<?php echo $this->getBaseURL()."report/exportCSV" ?>?tbl='+tbl+'&start='+start+'&end='+end);
    });
	$("body").on("click", ".btn-pdf", function(){
		var elem = $(this).attr("id");
		var tbl = elem[elem.length - 1];			
		var start = $("#start-date-"+tbl).val();
		var end   = $("#end-date-"+tbl).val();
		window.open('<?php echo $this->getBaseURL()."report/exportPDF" ?>?tbl='+tbl+'&start='+start+'&end='+end);
    });
});
$( function() {
    $(".date").datepicker()
        .datepicker("setDate", new Date())
		.datepicker("option", "dateFormat", "yy-mm-dd");
});
$(".date").datepicker({
    onSelect: function(d, i) {
		if (d !== i.lastVal){
			var elem = $(this).attr("id");
			var tbl = elem[elem.length - 1];			
			var start = $("#start-date-"+tbl).val();
			var end   = $("#end-date-"+tbl).val();
			$.ajax({
                url: "<?php echo $this->getBaseURL()."report/getLogs"; ?>",
                type: 'POST',
		    	data: {"tbl": tbl, "start": start, "end": end},
		    	success: 
				    function(data){
					    $("#tbl-"+tbl).html(data);
                    }
            });
        }
        
    }
});
</script>