<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div class="page-title-icon">
                <i class="pe-7s-car icon-gradient bg-mean-fruit">
                </i>
            </div>
            <div>Reports
                <div class="page-title-subheading">This is an example dashboard created using build-in elements and components.
                </div>
            </div>
        </div>
	</div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="main-card mb-3 card">
            <div class="card-body">
			    <h5 class="card-title">
				    Customers
			        <div class="dropdown d-inline-block float-r">
						<input type="text" id="tbl1_start" class="date tbl1_date" autocomplete="off" /> ~ 
						<input type="text" id="tbl1_end" class="date tbl1_date" autocomplete="off" />
                        <div tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu">
                            <button type="button" tabindex="0" class="dropdown-item">This Week</button>
                            <button type="button" tabindex="0" class="dropdown-item">This Month</button>
							<button type="button" tabindex="0" class="dropdown-item">This Year</button>
							<button type="button" tabindex="0" class="dropdown-item">All Time</button>
                        </div>
                    </div>
				</h5>
                <div id="customerTbl" class="table-responsive">
                    <table class="mb-0 table">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Date</th>
                            <th>No. of Customers</th>
                        </tr>
                        </thead>
                        <tbody>
						<?php foreach ($this->customerLogs  as $key=>$val): ?>
                        <tr>
                            <th scope="row"><?php echo $key+1; ?></th>
                            <td><?php echo $val["date"]; ?></td>
                            <td><?php echo $val["count"]; ?></td>
                        </tr>
						<?php endforeach ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
	<div class="col-lg-6">
        <div class="main-card mb-3 card">
            <div class="card-body">
			    <h5 class="card-title">
			        Top Seats
				 	 <div class="dropdown d-inline-block float-r">
                        <input type="text" id="tbl2_start" class="date" autocomplete="off" /> ~ 
						<input type="text" id="tbl2_end" class="date" autocomplete="off" />
                        <div tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu">
                            <button type="button" tabindex="0" class="dropdown-item">This Week</button>
                            <button type="button" tabindex="0" class="dropdown-item">This Month</button>
							<button type="button" tabindex="0" class="dropdown-item">This Year</button>
							<button type="button" tabindex="0" class="dropdown-item">All Time</button>
                        </div>
                    </div>
			    </h5>
                <div id="seatTbl" class="table-responsive">
                    <table class="mb-0 table">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Row</th>
							<th>Column</th>
                            <th>No. of Customers</th>
                        </tr>
                        </thead>
						<?php for($i=0; $i<10; $i++){ ?>
                        <tr>
                            <th scope="row"><?=$i+1?></th>
                            <td>Table cell</td>
                            <td>Table cell</td>
							<td>Table cell</td>
                        </tr>
						<?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
$( function() {
    $(".date").datepicker()
        .datepicker("setDate", new Date())
		.datepicker("option", "dateFormat", "yy-mm-dd");
});
$(".tbl1_date").datepicker({
    onSelect: function(d, i) {
		if (d !== i.lastVal){
			var start = $("#tbl1_start").val();
			var end   = $("#tbl1_end").val();
			$.ajax({
                url: "<?php echo $this->getBaseURL()."report/getCustomerLogs" ?>",
                type: 'POST',
		    	data: {"start": start, "end": end},
		    	success: 
				    function(data){
					    $("#customerTbl").html(data);
                    }
            });
        }
        
    }
});
</script>