<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div class="page-title-icon">
                <i class="pe-7s-car icon-gradient bg-mean-fruit">
                </i>
            </div>
            <div>Reports
                <div class="page-title-subheading">This is an example dashboard created using build-in elements and components.
                </div>
            </div>
        </div>
	</div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="main-card mb-3 card">
            <div class="card-body">
			    <h5 class="card-title">
				    Customers
			        <div class="dropdown d-inline-block float-r">
						<input type="text" id="start-date-1" class="date" autocomplete="off" /> ~ 
						<input type="text" id="end-date-1" class="date" autocomplete="off" />
                    </div>
				</h5>
                <div id="tbl-1" class="table-responsive">
                    <table class="mb-0 table">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Date</th>
                            <th>No. of Customers</th>
                        </tr>
                        </thead>
                        <tbody>
						<?php foreach ($this->customerLogs  as $key=>$val): ?>
                        <tr>
                            <th scope="row"><?php echo $key+1; ?></th>
                            <td><?php echo $val["date"]; ?></td>
                            <td><?php echo $val["count"]; ?></td>
                        </tr>
						<?php endforeach ?>
                        </tbody>
                    </table>
                    <ul class="pagination pagination-sm">
                        <li class="page-item"><a href="javascript:void(0);" class="page-link" aria-label="Previous"><span aria-hidden="true">«</span><span class="sr-only">Previous</span></a></li>
                        <li class="page-item active"><a href="javascript:void(0);" class="page-link">1</a></li>
                        <li class="page-item"><a href="javascript:void(0);" class="page-link">2</a></li>
                        <li class="page-item"><a href="javascript:void(0);" class="page-link">3</a></li>
                        <li class="page-item"><a href="javascript:void(0);" class="page-link" aria-label="Next"><span aria-hidden="true">»</span><span class="sr-only">Next</span></a></li>
                    </ul>
					<button class="mb-2 mr-2 btn btn-focus btn-export" id="export-1">Export</button>
                </div>
            </div>
        </div>
    </div>
	<div class="col-lg-6">
        <div class="main-card mb-3 card">
            <div class="card-body">
			    <h5 class="card-title">
			        Top Seats
				 	 <div class="dropdown d-inline-block float-r">
                        <input type="text" id="start-date-2" class="date" autocomplete="off" /> ~ 
						<input type="text" id="end-date-2" class="date" autocomplete="off" />
                    </div>
			    </h5>
                <div id="tbl-2" class="table-responsive">
                    <table class="mb-0 table">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Row</th>
							<th>Column</th>
                            <th>No. of Customers</th>
                        </tr>
                        </thead>
						<?php foreach ($this->seatLogs  as $key=>$val): ?>
                        <tr>
                            <th scope="row"><?php echo $key+1; ?></th>
                            <td><?php echo $val["row_no"]; ?></td>
                            <td><?php echo $val["col_no"]; ?></td>
							<td><?php echo $val["count"]; ?></td>
                        </tr>
						<?php endforeach ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
$(document).ready(function () {
    $(".btn-export").on("click", function(){
		var elem = $(this).attr("id");
		var tbl = elem[elem.length - 1];			
		var start = $("#start-date-"+tbl).val();
		var end   = $("#end-date-"+tbl).val();
		
		window.open('<?php echo $this->getBaseURL()."report/export" ?>?tbl='+tbl+'&start='+start+'&end='+end);
		/*$.ajax({
            url: "<?php echo $this->getBaseURL()."report/export" ?>",
            type: 'POST',
			data: {"tbl": tbl, "start": start, "end": end}
        });*/
    });
});
$( function() {
    $(".date").datepicker()
        .datepicker("setDate", new Date())
		.datepicker("option", "dateFormat", "yy-mm-dd");
});
$(".date").datepicker({
    onSelect: function(d, i) {
		if (d !== i.lastVal){
			var elem = $(this).attr("id");
			var tbl = elem[elem.length - 1];			
			var start = $("#start-date-"+tbl).val();
			var end   = $("#end-date-"+tbl).val();
			$.ajax({
                url: "<?php echo $this->getBaseURL()."report/getLogs"; ?>",
                type: 'POST',
		    	data: {"tbl": tbl, "start": start, "end": end},
		    	success: 
				    function(data){
					    $("#tbl-"+tbl).html(data);
                    }
            });
        }
        
    }
});
</script>