<div id="tbl-2" class="table-responsive">
    <table class="mb-0 table">
        <thead>
        <tr>
            <th>No.</th>
            <th>Row</th>
			<th>Column</th>
            <th>No. of Customers</th>
        </tr>
        </thead>
		<?php foreach ($this->seatLogs  as $key=>$val): ?>
        <tr>
            <th scope="row"><?php echo $key+1; ?></th>
            <td><?php echo $val["row_no"]; ?></td>
            <td><?php echo $val["col_no"]; ?></td>
			<td><?php echo $val["count"]; ?></td>
        </tr>
		<?php endforeach ?>
        </tbody>
    </table>
</div>