<div id="tbl-2" class="table-responsive">
    <table class="mb-0 table">
        <thead>
        <tr>
            <th>No.</th>
            <th>Row</th>
			<th>Column</th>
            <th>No. of Customers</th>
        </tr>
        </thead>
		<?php foreach ($this->seatLogs  as $key=>$val): ?>
        <tr>
            <th scope="row"><?php echo $key+1; ?></th>
            <td><?php echo $val["row_no"]; ?></td>
            <td><?php echo $val["col_no"]; ?></td>
			<td><?php echo $val["count"]; ?></td>
        </tr>
		<?php endforeach ?>
        </tbody>
    </table>
	<div class="m-t-20 t-center">
		<button class="mb-2 mr-2 btn btn-dark btn-csv" id="btn-csv-2">Export CSV</button>
		<button class="mb-2 btn btn-dark btn-pdf" id="btn-pdf-2">Generate PDF</button>
	</div>
</div>