
<section class="bgwhite p-t-66 p-b-60">
	<div class="container register" style="max-width:500px">
		<div class="row">
			<div class="col-md-12 p-b-30">
				<form id="register">
					<h4 class="m-text26 p-b-36 p-t-15">
						Create an Account
					</h4>
					<div class="bo4 of-hidden size15 m-b-20">
						<input class="sizefull s-text7 p-l-22 p-r-22" type="text" name="username" placeholder="Username">
					</div>
					<div class="bo4 of-hidden size15 m-b-20">
						<input class="sizefull s-text7 p-l-22 p-r-22" type="password" name="password1" placeholder="Password">
					</div>
					<div class="bo4 of-hidden size15 m-b-20">
						<input class="sizefull s-text7 p-l-22 p-r-22" type="password" name="password2" placeholder="Re-enter Password">
					</div>
					<div class="bo4 of-hidden size15 m-b-20">
						<input class="sizefull s-text7 p-l-22 p-r-22" type="text" name="email" placeholder="Email Address">
					</div>
					<div class="w-size25">
						<button class="flex-c-m size2 bg1 bo-rad-23 hov1 m-text3 trans-0-4">Register</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>
<script type="text/javascript">
    $(document).ready(function () {
		/* Register */
		$("#register").submit(function(e){
		    e.preventDefault();
            var form = $(this);
		    $.ajax({
		    	url: "<?php echo $this->getControllerURL('register', 'save'); ?>",
                type: 'POST',
		    	data: form.serialize(),
		    	success:
		    	    function(result){
						if (result == "ok") {
							$(location).attr('href', '<?php echo $this->getSiteURL();?>/admin');
						} else {
							alert("Incorrect username/password. Please try again.");
						}
                    }
            });
        });
    });
</script>