<script type="text/javascript">
$(document).ready(function () {
	/* Get Search Result */
	$("#filterBtn").on("click", function(){
		search();
    });
    $("#name, #address, #sort").on("change", function(){
		search();
    });
	function search(){
		var name    = $("#name").val();
		var address = $("#address").val();
		var sort    = $("#sort").val();
		$.ajax({
            url: "<?php echo $this->getBaseURL()."/catalog/search"; ?>",
            type: 'get',
			data : {"name": name, 'address': address, "sort": sort},
			success:
			    function(data){
					$("#result").html(data);
                }
        });
	}
});
</script>
<!-- Title Page -->
<section class="bg-title-page p-t-50 p-b-40 flex-col-c-m" style="background-image: url(assets/images/banner-catalog.jpg);">
	<h2 class="l-text2 t-center">Makakaupo</h2>
	<p class="m-text13 t-center">Find available seats</p>
</section>
<!-- Content page -->
<section class="bgwhite p-t-55 p-b-65">
	<div class="container">
		<div class="row">
			<div class="col-sm-6 col-md-8 col-lg-12 p-b-50">
				<div class="flex-sb-m flex-w p-b-35">
					<div class="flex-w">
						<div class="rs2-select2 bo4 of-hidden w-size12 m-t-5 m-b-5 m-r-10 pos-relative">
							<input type="text" id="name" class="sizefull s-text7 p-l-22 p-r-22" value="<?php echo $this->name;?>" placeholder="Restaurant Name">
							<button id="filterBtn" class="flex-c-m size5 ab-r-m color2 color0-hov trans-0-4">
								<i class="fs-12 fa fa-search" aria-hidden="true"></i>
							</button>
						</div>
						<div class="rs2-select2 bo4 of-hidden w-size12 m-t-5 m-b-5 m-r-10 pos-relative">
							<input type="text" id="address" class="sizefull s-text7 p-l-22 p-r-22" value="<?php echo $this->address;?>" placeholder="Location">
							<button id="filterBtn" class="flex-c-m size5 ab-r-m color2 color0-hov trans-0-4">
								<i class="fs-12 fa fa-search" aria-hidden="true"></i>
							</button>
						</div>
						<div class="rs2-select2 bo4 of-hidden w-size12 m-t-5 m-b-5 m-r-10">
							<select id="sort" class="selection-1">
							    <option disabled>Sort by:</option>
								<option value="vacant" <?php echo ($this->sort == "vacant") ? "selected" : ""; ?>>Vacant Seats</option>
								<option value="total" <?php echo ($this->sort == "total") ? "selected" : ""; ?>>Total No. of Seats</option>
							</select>
						</div>
					</div>
				</div>
				<!-- Search Result -->
				<div id="result">
				    <span class="s-text8 p-t-5 p-b-5">Showing 1–12 of 16 results</span>
			        <!-- Restaurants -->
				    <div class="row">
				        <?php foreach($this->restaurants as $restaurant):?>
				    	    <div class="col-sm-12 col-md-6 col-lg-4 p-b-50">
				    		    <div class="block2">
				    		        <a href="restaurant">
				    		        	<div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
				    		        	    <img src="<?php echo $this->getAssetsURL().'/images/restaurants/'.$restaurant['image']; ?>" alt="IMG-PRODUCT">
				    		    			<div class="block2-overlay trans-0-4"></div>
				    		        	</div>
				    		        	<div class="block2-txt p-t-20">
				    		        	    <span class="block2-price s-text3 dis-block"><?php echo $restaurant['restaurant_name'];?></span>
				    		        		<span class="block2-price s-text3"><?php echo $restaurant['address'];?></span>
				    		        	</div>
				    		    	</a>
				    		    </div>
				    		
				    	    </div>
				    	<?php endforeach ?>
				    </div>
				    <!-- Pagination -->
				    <div class="pagination flex-m flex-w p-t-26">
				    	<a href="#" class="item-pagination flex-c-m trans-0-4 active-pagination">1</a>
				    	<a href="#" class="item-pagination flex-c-m trans-0-4">2</a>
				    </div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Container Selection -->
<div id="dropDownSelect1"></div>
<script type="text/javascript" src="vendor/bootstrap/js/popper.js"></script>
<script type="text/javascript" src="vendor/select2/select2.min.js"></script>
<script type="text/javascript">
	$(".selection-1").select2({
		minimumResultsForSearch: 20,
		dropdownParent: $('#dropDownSelect1')
	});
</script>
<script type="text/javascript" src="vendor/daterangepicker/moment.min.js"></script>
<script type="text/javascript" src="vendor/daterangepicker/daterangepicker.js"></script>
<script type="text/javascript" src="vendor/slick/slick.min.js"></script>
<script type="text/javascript" src="js/slick-custom.js"></script>
<script type="text/javascript" src="vendor/sweetalert/sweetalert.min.js"></script>