<span class="s-text8 p-t-5 p-b-5">Showing 1–12 of 16 results</span>
<!-- Restaurants -->
<div class="row">
    <?php foreach($this->restaurants as $restaurant):?>
	    <div class="col-sm-12 col-md-6 col-lg-4 p-b-50">
		    <div class="block2">
		        <a href="restaurant">
		        	<div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
		        	    <img src="<?php echo $this->getAssetsURL().'/images/restaurants/'.$restaurant['image']; ?>" alt="IMG-PRODUCT">
		    			<div class="block2-overlay trans-0-4"></div>
		        	</div>
		        	<div class="block2-txt p-t-20">
		        	    <span class="block2-price s-text3 dis-block"><?php echo $restaurant['restaurant_name'];?></span>
		        		<span class="block2-price s-text3"><?php echo $restaurant['address'];?></span>
		        	</div>
		    	</a>
		    </div>
		
	    </div>
	<?php endforeach ?>
</div>
<!-- Pagination -->
<div class="pagination flex-m flex-w p-t-26">
	<a href="#" class="item-pagination flex-c-m trans-0-4 active-pagination">1</a>
	<a href="#" class="item-pagination flex-c-m trans-0-4">2</a>
</div>