<!DOCTYPE html>
<html lang="en">
<head>
	<title>Makakaupo</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/png" href="<?php echo $this->getAssetsURL();?>/images/icons/favicon.png"/>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getAssetsURL();?>/vendor/bootstrap/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getAssetsURL();?>/fonts/font-awesome-4.7.0/css/font-awesome.min.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getAssetsURL();?>/fonts/themify/themify-icons.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getAssetsURL();?>/fonts/Linearicons-Free-v1.0.0/icon-font.min.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getAssetsURL();?>/fonts/elegant-font/html-css/style.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getAssetsURL();?>/vendor/animate/animate.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getAssetsURL();?>/vendor/css-hamburgers/hamburgers.min.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getAssetsURL();?>/vendor/animsition/css/animsition.min.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getAssetsURL();?>/vendor/select2/select2.min.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getAssetsURL();?>/vendor/daterangepicker/daterangepicker.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getAssetsURL();?>/vendor/slick/slick.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getAssetsURL();?>/vendor/lightbox2/css/lightbox.min.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getAssetsURL();?>/css/util.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getAssetsURL();?>/css/main.css" />
    <script type="text/javascript" src="<?php echo $this->getAssetsURL();?>/vendor/jquery/jquery-3.2.1.min.js"></script>
	<!-- Mapbox -->
    <script src="https://api.mapbox.com/mapbox-gl-js/v1.9.1/mapbox-gl.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v1.9.1/mapbox-gl.css" rel="stylesheet" />
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.4.2/mapbox-gl-geocoder.min.js"></script>
    <!-- Promise polyfill script required to use Mapbox GL Geocoder in IE 11 -->
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.4.2/mapbox-gl-geocoder.css" type="text/css" />
</head>
<body>
 <!-- HEADER -->
    <header class="header1">
    	<div class="container-menu-header">
			<div class="topbar">
				<span><?php echo (isset($this->verifyMsg)) ? $this->verifyMsg : "" ;?></span>
			</div>
    		<div class="wrap_header">
    			<a href="<?php echo $this->getBaseURL();?>" class="logo">
    				<img src="<?php echo $this->getAssetsURL();?>/images/icons/logo.png" alt="IMG-LOGO">
    			</a>
				<div class="header-account">
				    <form class="login form-inline">
                        <div class="position-relative form-group bo4 mr-2">
                            <label for="username" class="sr-only">Username</label>
                            <input name="username" placeholder="Username" type="username" class="form-control">
                        </div>
                        <div class="position-relative form-group bo4 mr-2">
                            <label for="password" class="sr-only">Password</label>
                            <input name="password" placeholder="Password" type="password" class="form-control">
                        </div>
                        <button class="btn btn-dark mr-2">Login</button>
						<button class="btn btn-dark" onclick="location.href='<?php echo $this->getControllerURL('user', 'register'); ?>'">Register</button>
                    </form>
				</div>
    		</div>
    	</div>
    	<!-- Header Mobile -->
    	<div class="wrap_header_mobile">
    		<!-- Logo mobile -->
    		<a href="index.html" class="logo-mobile">
    			<img src="<?php echo $this->getAssetsURL();?>/images/icons/logo.png" alt="IMG-LOGO">
    		</a>
			<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
				<span class="hamburger-box">
					<span class="hamburger-inner"></span>
				</span>
			</div>
    	</div>
		<!-- Menu Mobile -->
		<div class="wrap-side-menu" >
			<nav class="side-menu">
			    <form class="login">
				    <ul class="main-menu">
				    	<li class="item-topbar-mobile p-l-15 p-r-15 p-t-8 p-b-8">
						    <div id="mobile-login">
				    		    <div id="mobile-username" class="bo4">
                                    <label for="username" class="sr-only">Username</label>
                                    <input name="username" placeholder="Username" type="username" class="form-control">
                                </div>
							    <div id="mobile-password" class="bo4">
                                    <label for="password" class="sr-only">Password</label>
                                    <input name="password" placeholder="Password" type="password" class="form-control">
                                </div>
							</div>
				    	</li>
				    	<li class="item-topbar-mobile p-t-8 p-b-8">
						    <div class="flex-c-m">
				    		    <button class="btn btn-dark mr-2">Login</button>
				    	        <button onclick="location.href='<?php echo $this->getControllerURL('user', 'register'); ?>'" class="btn btn-dark">Register</button>
							</div>
				    	</li>
				    </ul>
				</form>
			</nav>
		</div>
    </header>
	<!-- MAIN CONTENT -->
	<div id="conntent"><?php echo $this->contents; ?></div>
	<!-- FOOTER -->
    <footer class="bg6 p-t-45 p-b-43 p-l-45 p-r-45">
    	<div class="t-center p-l-15 p-r-15">
    		<div class="t-center s-text8 p-t-20">Copyright © 2018 Colorlib</div>
    	</div>
    </footer>
	<!-- BACK TO TOP -->
    <div class="btn-back-to-top bg0-hov" id="myBtn">
    	<span class="symbol-btn-back-to-top">
    		<i class="fa fa-angle-double-up" aria-hidden="true"></i>
    	</span>
    </div>
	<!-- JS FILE -->
	<script type="text/javascript" src="<?php echo $this->getAssetsURL();?>/vendor/animsition/js/animsition.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->getAssetsURL();?>/vendor/bootstrap/js/popper.js"></script>
	<script type="text/javascript" src="<?php echo $this->getAssetsURL();?>/vendor/bootstrap/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->getAssetsURL();?>/vendor/select2/select2.min.js"></script>
	<script type="text/javascript">
		$(".selection-1").select2({
	    	minimumResultsForSearch: 20,
	    	dropdownParent: $('#dropDownSelect1')
	    });
	    $(".selection-2").select2({
	    	minimumResultsForSearch: 20,
	    	dropdownParent: $('#dropDownSelect2')
	    });
	</script>
	<script type="text/javascript" src="<?php echo $this->getAssetsURL();?>/vendor/slick/slick.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->getAssetsURL();?>/js/slick-custom.js"></script>
	<script type="text/javascript" src="<?php echo $this->getAssetsURL();?>/vendor/countdowntime/countdowntime.js"></script>
	<script type="text/javascript" src="<?php echo $this->getAssetsURL();?>/vendor/lightbox2/js/lightbox.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->getAssetsURL();?>/vendor/sweetalert/sweetalert.min.js"></script>
	<script type="text/javascript">
		$('.block2-btn-addcart').each(function(){
			var nameProduct = $(this).parent().parent().parent().find('.block2-name').html();
			$(this).on('click', function(){
				swal(nameProduct, "is added to cart !", "success");
			});
		});

		$('.block2-btn-addwishlist').each(function(){
			var nameProduct = $(this).parent().parent().parent().find('.block2-name').html();
			$(this).on('click', function(){
				swal(nameProduct, "is added to wishlist !", "success");
			});
		});
	</script>
	<script type="text/javascript" src="<?php echo $this->getAssetsURL();?>/vendor/parallax100/parallax100.js"></script>
	<script type="text/javascript">
        $('.parallax100').parallax100();
	</script>
	<script src="<?php echo $this->getAssetsURL();?>/js/main.js"></script>
	<script type="text/javascript">
    $(document).ready(function () {
		/* Login */
		$(".login").submit(function(e){
		    e.preventDefault();
            var form = $(this);
		    $.ajax({
		    	url: "<?php echo $this->getControllerURL('user', 'checkLogin'); ?>",
                type: 'POST',
		    	data: form.serialize(),
		    	success:
		    	    function(result){
						switch(result){
							case "-1":  // Unverified Account
							    $(location).attr('href', '<?php echo $this->getSiteURL();?>/admin/profile');
								break;
							case "0":   // Verified Account
							    $(location).attr('href', '<?php echo $this->getSiteURL();?>/admin/status');
								break;
						    case "1":
							    alert("Incorrect username/password.");
								break;
							case "2":
							    alert("Please enter both username and password.");
							default: break;
						}
                    }
            });
        });
    });
    </script>
</body>
</html>

