<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div class="page-title-icon">
                <i class="pe-7s-car icon-gradient bg-mean-fruit">
                </i>
            </div>
            <div>Seat Layout Creator
                <div class="page-title-subheading">This is an example dashboard created using build-in elements and components.
                </div>
            </div>
        </div>
	</div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-6">
		<div class="w-size13 p-t-30 respon5">
			<div class="wrap-slick3 flex-sb flex-w">
				<div class="wrap-slick3-dots"></div>
				<div class="slick3">
					<div class="item-slick3" data-thumb="assets/images/thumb-item-01.jpg">
						<div class="wrap-pic-w">
							<img src="assets/images/product-detail-01.jpg" alt="IMG-PRODUCT">
						</div>
					</div>
					<div class="item-slick3" data-thumb="assets/images/thumb-item-02.jpg">
						<div class="wrap-pic-w">
							<img src="assets/images/product-detail-02.jpg" alt="IMG-PRODUCT">
						</div>
					</div>
					<div class="item-slick3" data-thumb="assets/images/thumb-item-03.jpg">
						<div class="wrap-pic-w">
							<img src="assets/images/product-detail-03.jpg" alt="IMG-PRODUCT">
						</div>
					</div>
				</div>
			</div>
		</div>
    </div>
</div>