<section class="bgwhite p-t-30 p-b-30">
	<div class="container register" style="max-width:450px">
		<div class="row">
			<div class="col-md-12">
				<form id="register" method="post">
					<h4 class="m-text26 p-b-20">Create an Account</h4>
					<div class="bo4 of-hidden size15 m-b-20">
						<input class="sizefull s-text7 p-l-22 p-r-22" type="text" name="username" placeholder="Username" maxlength="50">
					</div>
					<div class="bo4 of-hidden size15 m-b-20">
						<input class="sizefull s-text7 p-l-22 p-r-22" type="password" name="password1" placeholder="Password" minlength="8" maxlength="100">
					</div>
					<div class="bo4 of-hidden size15 m-b-20">
						<input class="sizefull s-text7 p-l-22 p-r-22" type="password" name="password2" placeholder="Confirm Password" minlength="8" maxlength="100">
					</div>
					<div class="bo4 of-hidden size15 m-b-20">
						<input class="sizefull s-text7 p-l-22 p-r-22" type="email" name="email" placeholder="Email Address">
					</div>
					<div class="flex-c">
						<button class="w-size25 size2 bg1 bo-rad-23 hov1 m-text3 trans-0-4">Register</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>
<script type="text/javascript">
$(document).ready(function () {
	$("#register").submit(function(e){
	    e.preventDefault();
        var form = $(this);
	    $.ajax({
	    	url: "<?php echo $this->getControllerURL('user', 'add'); ?>",
            type: 'POST',
	    	data: form.serialize(),
	    	success:
	    	    function(result){
					switch(result){
					    case "0":
						    swal("Success!", "Thank you for registering to our website. An email verification has been sent to your account.", "success");
							break;
						case "1":
							swal("Registration Error", "Please fill out all fields.", "error");
							break;
						case "2":
							swal("Registration Error", "Username has already been taken.", "error");
							break;
						case "3":
							swal("Registration Error", "Please enter a matching password and confirmation password.", "error");
							break;
						case "4":
							swal("Registration Error", "An error occurred during the registration. Please try again.", "error");
							break;
						case "5":
							swal("Registration Error", "An error occured while sending the email.", "error");
							break;
						default: break;
					}
                },
			fail:
				function(){
				    swal("Registration Error", "Something went wrong. Please try again.", "error");
				}
        });
    });
});
</script>