<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div class="page-title-icon">
                <i class="pe-7s-car icon-gradient bg-mean-fruit">
                </i>
            </div>
            <div>Reports
                <div class="page-title-subheading">This is an example dashboard created using build-in elements and components.
                </div>
            </div>
        </div>
	</div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="main-card mb-3 card">
            <div class="card-body">
			    <h5 class="card-title">
				    Customers
			        <div class="dropdown d-inline-block float-r">
                        <button type="button" aria-haspopup="true" aria-expanded="false" data-toggle="dropdown" class="mb-2 mr-2 dropdown-toggle btn btn-light btn-sm">This Week</button>
                        <div tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu">
                            <button type="button" tabindex="0" class="dropdown-item">This Week</button>
                            <button type="button" tabindex="0" class="dropdown-item">This Month</button>
							<button type="button" tabindex="0" class="dropdown-item">This Year</button>
							<button type="button" tabindex="0" class="dropdown-item">All Time</button>
                        </div>
                    </div>
				</h5>
                <div class="table-responsive">
                    <table class="mb-0 table">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Date</th>
                            <th>No. of Customers</th>
                        </tr>
                        </thead>
                        <tbody>
						<?php for($i=0; $i<10; $i++){ ?>
                        <tr>
                            <th scope="row"><?=$i+1?></th>
                            <td>Table cell</td>
                            <td>Table cell</td>
                        </tr>
						<?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
	<div class="col-lg-6">
        <div class="main-card mb-3 card">
            <div class="card-body">
			    <h5 class="card-title">
			        Top Seats
				 	 <div class="dropdown d-inline-block float-r">
                        <button type="button" aria-haspopup="true" aria-expanded="false" data-toggle="dropdown" class="mb-2 mr-2 dropdown-toggle btn btn-light btn-sm">Today</button>
                        <div tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu">
                            <button type="button" tabindex="0" class="dropdown-item">This Week</button>
                            <button type="button" tabindex="0" class="dropdown-item">This Month</button>
							<button type="button" tabindex="0" class="dropdown-item">This Year</button>
							<button type="button" tabindex="0" class="dropdown-item">All Time</button>
                        </div>
                    </div>
			    </h5>
                <div class="table-responsive">
                    <table class="mb-0 table">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Row</th>
							<th>Column</th>
                            <th>No. of Customers</th>
                        </tr>
                        </thead>
						<?php for($i=0; $i<10; $i++){ ?>
                        <tr>
                            <th scope="row"><?=$i+1?></th>
                            <td>Table cell</td>
                            <td>Table cell</td>
							<td>Table cell</td>
                        </tr>
						<?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>