<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta http-equiv="Cache-control" content="public">
    <title>Makakaupo - Administrator Tool</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <meta name="description" content="This is an example dashboard created using build-in elements and components.">
    <meta name="msapplication-tap-highlight" content="no">
    <link href="assets/main.css" rel="stylesheet">
    <link href="assets/css/main.css" rel="stylesheet">
	<link href="assets/css/util.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="assets/vendor/slick/slick.css">
	<script type="text/javascript" src="assets/vendor/jquery/jquery-3.2.1.min.js"></script>
	<script defer type="text/javascript" src="assets/vendor/slick/slick.min.js"></script>
	<script defer type="text/javascript" src="assets/js/slick-custom.js"></script>
	<script defer type="text/javascript" src="assets/js/main.js"></script>
</head>
<body>
    <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
        <div class="app-header header-shadow">
            <div class="app-header__logo" style="width:auto; display:flex;">
			    <a href="<?php echo $this->getSiteURL();?>">
                    <div class="logo-src"></div>
				</a>
                <div class="header__pane ml-auto" style="display:none;">
                    <div>
                        <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="app-header__mobile-menu">
                <div>
                    <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                    </button>
                </div>
            </div>
            <div class="app-header__menu">
                <span>
                    <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                        <span class="btn-icon-wrapper">
                            <i class="fa fa-ellipsis-v fa-w-6"></i>
                        </span>
                    </button>
                </span>
            </div>
			<div class="app-header__content">
                <div class="app-header-right">
                    <div class="header-btn-lg pr-0">
                        <div class="widget-content p-0">
                            <div class="widget-content-wrapper">
                                <div class="widget-content-left">
                                    <div class="btn-group">
                                        <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="p-0 btn">
                                            <i class="fa fa-angle-down ml-2 opacity-8"></i>
                                        </a>
                                        <div tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu dropdown-menu-right">
                                            <button type="button" tabindex="0" class="dropdown-item" 
											        onclick="location.href='<?php echo $this->getControllerURL('logout'); ?>'">Logout
										    </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
				</div>
            </div>
        </div>
		<div class="app-main">
            <div class="app-sidebar sidebar-shadow">
                <div class="app-header__logo">
				    <a href="<?php echo $this->getSiteURL();?>">
                        <div class="logo-src"></div>
					</a>
                    <div class="header__pane ml-auto">
                        <div>
                            <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                                <span class="hamburger-box">
                                    <span class="hamburger-inner"></span>
                                </span>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="app-header__mobile-menu">
                    <div>
                        <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
                <div class="app-header__menu">
                    <span>
                        <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                            <span class="btn-icon-wrapper">
                                <i class="fa fa-ellipsis-v fa-w-6"></i>
                            </span>
                        </button>
                    </span>
                </div>
                <div class="scrollbar-sidebar">

                    <div class="app-sidebar__inner">
                        <ul class="vertical-nav-menu">
                            <li class="app-sidebar__heading">Dashboards</li>
							<li class="<?php echo ($_SESSION['is_verified'] == 0) ? 'disabled' : ''?>">
                                <a class="<?=($this->menu == "status")?"mm-active":""?>" href="<?php echo $this->getBaseURL()."status"; ?>">
                                    <i class="metismenu-icon pe-7s-mouse"></i>Seat Status 
                                </a>
                            </li>
                            <li class="<?php echo ($_SESSION['is_verified'] == 0) ? 'disabled' : ''?>">
							    <a class="<?=($this->menu == "layout")?"mm-active":""?>" href="<?php echo $this->getBaseURL()."layout"; ?>">
								    <i class="metismenu-icon pe-7s-pen"></i>Seat Layout Creator
								</a>
							</li>
                            <li>
							    <a class="<?=($this->menu == "profile")?"mm-active":""?>" href="<?php echo $this->getBaseURL()."profile"; ?>">
							        <i class="metismenu-icon pe-7s-note2"></i>Restaurant Profile
								</a>
							</li>
                            <li>
                                <a class="<?=($this->menu == "user")?"mm-active":""?>" href="<?php echo $this->getBaseURL()."user"; ?>">
                                    <i class="metismenu-icon pe-7s-diamond"></i>User Account
                                </a>
                            </li>
							<li class="<?php echo ($_SESSION['is_verified'] == 0) ? 'disabled' : ''?>">
                                <a class="<?=($this->menu == "report")?"mm-active":""?>" href="<?php echo $this->getBaseURL()."report"; ?>">
                                    <i class="metismenu-icon pe-7s-display2"></i>Reports
                                </a>
                            </li>
                        </ul>
                        <?php if ($_SESSION['is_verified'] == 0){?>
                            <div class="t-center">
                                <span class="color0">
                                    Please verify your account<br/>to access all features.
                                </span>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
			<div class="app-main__outer">
	            <!-- MAIN CONTENT -->
				<div class="app-main__inner"><?php echo $this->contents; ?></div>
			</div>
        </div>
    </div>
</body>
</html>
<!--
=========================================================
* ArchitectUI HTML Theme Dashboard - v1.0.0
=========================================================
* Product Page: https://dashboardpack.com
* Copyright 2019 DashboardPack (https://dashboardpack.com)
* Licensed under MIT (https://github.com/DashboardPack/architectui-html-theme-free/blob/master/LICENSE)
=========================================================
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->