<section class="slide1">
	<div class="wrap-slick1">
		<div class="slick1">
		    <form id="search" action="<?php echo $this->getBaseURL()."/catalog"; ?>" method="get">
			<div class="item-slick1 item1-slick1" style="background-image: url(assets/images/master-slide-07.jpg);">
				<div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">
					<h2 class="caption1-slide1 xl-text2 t-center bo14 p-b-6 animated visible-false m-b-22" data-appear="fadeInUp">
						Find your seat
					</h2>
					<div class="size11 bo4">
				    	<input class="sizefull s-text7 p-l-22 p-r-22" type="text" name="filter" placeholder="Name or Location">
				    </div>
					<div class="size25 trans-0-4 m-t-10 m-b-10">
				    	<button class="flex-c-m sizefull bgwhite bo-rad-23 hov1 s-text2">Search</button>
				    </div>
				</div>
			</div>
			</form>
		</div>
	</div>
</section>
<!-- New Restaurants -->
<div class="banner bgwhite p-t-10 p-b-20">
	<div class="container">
		<div class="sec-title p-b-22">
			<h3 class="m-text5 t-center">New Restaurants</h3>
		</div>
		<div class="row">
		    <?php foreach($this->newRestaurants as $newRestaurant):?>
			<div class="col-sm-10 col-md-8 col-lg-4 m-l-r-auto">
				<?php echo $newRestaurant['restaurant_name'];?>
				<div class="block1 hov-img-zoom pos-relative m-b-30">
				    <a href="restaurant">
					    <img src="assets/images/banner-05.jpg" alt="IMG-BENNER">
					</a>
				</div>
			</div>
			<?php endforeach ?>
		</div>
	</div>
</div>