<!-- Slide1 -->
<section class="slide1">
	<div class="wrap-slick1">
		<div class="slick1">
			<div class="item-slick1 item1-slick1" style="background-image: url(assets/images/master-slide-07.jpg);">
				<div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">
					<h2 class="caption1-slide1 xl-text2 t-center bo14 p-b-6 animated visible-false m-b-22" data-appear="fadeInUp">
						Find your seat
					</h2>
					<span class="caption2-slide1 m-text1 t-center animated visible-false m-b-33" data-appear="fadeInDown">
						New Collection 2018
					</span>
					<div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="zoomIn">
						<!-- Button -->
						<a href="restaurants.html" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4">
							Find Now
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Banner -->
<div class="banner bgwhite p-t-40 p-b-30">
	<div class="container">
		<div class="row">
			<div class="col-sm-10 col-md-8 col-lg-4 m-l-r-auto">
				<!-- block1 -->
				<div class="block1 hov-img-zoom pos-relative m-b-30">
				    <a href="restaurant">
					    <img src="assets/images/banner-05.jpg" alt="IMG-BENNER">
					</a>
				</div>
			</div>
			<div class="col-sm-10 col-md-8 col-lg-4 m-l-r-auto">
				<!-- block1 -->
				<div class="block1 hov-img-zoom pos-relative m-b-30">
				    <a href="restaurant">
					    <img src="assets/images/banner-05.jpg" alt="IMG-BENNER">
					</a>
				</div>
			</div>
			<div class="col-sm-10 col-md-8 col-lg-4 m-l-r-auto">
				<!-- block1 -->
				<div class="block1 hov-img-zoom pos-relative m-b-30">
				    <a href="restaurant">
					    <img src="assets/images/banner-05.jpg" alt="IMG-BENNER">
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Restaurants -->
<section class="bgwhite p-t-30 p-b-58">
	<div class="container">
		<div class="sec-title p-b-22">
			<h3 class="m-text5 t-center">
				Restaurants
			</h3>
		</div>
		<!-- Tab01 -->
		<div class="tab01">
			<!-- Nav tabs -->
			<ul class="nav nav-tabs" role="tablist">
				<li class="nav-item">
					<a class="nav-link active" data-toggle="tab" href="#best-seller" role="tab">Best Seller</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" data-toggle="tab" href="#featured" role="tab">Featured</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" data-toggle="tab" href="#sale" role="tab">Sale</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" data-toggle="tab" href="#top-rate" role="tab">Top Rate</a>
				</li>
			</ul>
			<!-- Tab panes -->
			<div class="tab-content p-t-35">
				<!-- - -->
				<div class="tab-pane fade show active" id="best-seller" role="tabpanel">
					<div class="row">
						<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
							<!-- Block2 -->
							<div class="block2">
							    <a href="<?php echo $this->getControllerURL('restaurant').'/1';?>">
							    	<div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
							    	    <img src="assets/images/item-02.jpg" alt="IMG-PRODUCT">
										<div class="block2-overlay trans-0-4"></div>
							    	</div>
							    	<div class="block2-txt p-t-20">
							    	    <span class="block2-price s-text3 dis-block">Jobeeli</span>
							    		<span class="block2-price s-text3">Cainta</span>
							    	</div>
								</a>
							</div>
						</div>
						<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
							<!-- Block2 -->
							<div class="block2">
							    <a href="restaurant">
							    	<div class="block2-img wrap-pic-w of-hidden pos-relative">
							    	    <img src="assets/images/item-02.jpg" alt="IMG-PRODUCT">
										<div class="block2-overlay trans-0-4"></div>
							    	</div>
							    	<div class="block2-txt p-t-20">
							    	    <span class="block2-price s-text3 dis-block">Mang Donaldo</span>
							    		<span class="block2-price s-text3">Laguna</span>
							    	</div>
								</a>
							</div>
						</div>
						<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
							<!-- Block2 -->
							<div class="block2">
							    <a href="restaurant">
							    	<div class="block2-img wrap-pic-w of-hidden pos-relative">
							    	    <img src="assets/images/item-02.jpg" alt="IMG-PRODUCT">
										<div class="block2-overlay trans-0-4"></div>
							    	</div>
							    	<div class="block2-txt p-t-20">
							    	    <span class="block2-price s-text3 dis-block">KMC</span>
							    		<span class="block2-price s-text3">Batangas</span>
							    	</div>
								</a>
							</div>
						</div>
						<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
							<!-- Block2 -->
							<div class="block2">
							    <a href="restaurant">
							    	<div class="block2-img wrap-pic-w of-hidden pos-relative">
							    	    <img src="assets/images/item-02.jpg" alt="IMG-PRODUCT">
										<div class="block2-overlay trans-0-4"></div>
							    	</div>
							    	<div class="block2-txt p-t-20">
							    	    <span class="block2-price s-text3 dis-block">KMC</span>
							    		<span class="block2-price s-text3">Batangas</span>
							    	</div>
								</a>
							</div>
						</div>

						<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
							<!-- Block2 -->
							<div class="block2">
							    <a href="restaurant">
							    	<div class="block2-img wrap-pic-w of-hidden pos-relative">
							    	    <img src="assets/images/item-02.jpg" alt="IMG-PRODUCT">
										<div class="block2-overlay trans-0-4"></div>
							    	</div>
							    	<div class="block2-txt p-t-20">
							    	    <span class="block2-price s-text3 dis-block">KMC</span>
							    		<span class="block2-price s-text3">Batangas</span>
							    	</div>
								</a>
							</div>
						</div>
						<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
							<!-- Block2 -->
							<div class="block2">
							    <a href="restaurant">
							    	<div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
							    	    <img src="assets/images/item-02.jpg" alt="IMG-PRODUCT">
										<div class="block2-overlay trans-0-4"></div>
							    	</div>
							    	<div class="block2-txt p-t-20">
							    	    <span class="block2-price s-text3 dis-block">Jobeeli</span>
							    		<span class="block2-price s-text3">Cainta</span>
							    	</div>
								</a>
							</div>
						</div>
						<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
							<!-- Block2 -->
							<div class="block2">
							    <a href="restaurant">
							    	<div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
							    	    <img src="assets/images/item-02.jpg" alt="IMG-PRODUCT">
										<div class="block2-overlay trans-0-4"></div>
							    	</div>
							    	<div class="block2-txt p-t-20">
							    	    <span class="block2-price s-text3 dis-block">Jobeeli</span>
							    		<span class="block2-price s-text3">Cainta</span>
							    	</div>
								</a>
							</div>
						</div>
						<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
							<!-- Block2 -->
							<div class="block2">
							    <a href="restaurant">
							    	<div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelsale">
							    	    <img src="assets/images/item-02.jpg" alt="IMG-PRODUCT">
										<div class="block2-overlay trans-0-4"></div>
							    	</div>
							    	<div class="block2-txt p-t-20">
							    	    <span class="block2-price s-text3 dis-block">Jobeeli</span>
							    		<span class="block2-price s-text3">Cainta</span>
							    	</div>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Container Selection1 -->
<div id="dropDownSelect1"></div>