<section class="slide1">
	<div class="wrap-slick1">
		<div class="slick1">
		    <form id="search" action="<?php echo $this->getBaseURL()."/catalog"; ?>" method="get">
			<div class="item-slick1 item1-slick1" style="background-image: url(<?php echo $this->getAssetsURL().'/images/banner-home.jpg'; ?>);">
				<div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">
					<h2 class="caption1-slide1 xl-text2 t-center bo14 p-b-6 animated visible-false m-b-22" data-appear="fadeInUp">
						Makakaupo
					</h2>
					<span class="caption2-slide1 m-text9 t-center animated visible-false m-b-20" data-appear="fadeInDown">
						Find your seat
					</span>
					<div class="size11 bo4 m-b-10">
				    	<input class="sizefull s-text7 p-l-22 p-r-22" type="text" name="name" placeholder="Restaurant Name" />
				    </div>
				    <div class="size11 m-b-10">
						<div id="map"></div>
                        <div id="geocoder" class="geocoder"></div>
						<input type="hidden" id="address" name="address" />
	            	    <input type="hidden" id="longitude" name="longitude" />
	            	    <input type="hidden" id="latitude" name="latitude" />
				    </div>
					<div class="size25 trans-0-4 m-t-10 m-b-10">
				    	<button class="flex-c-m sizefull bgwhite bo-rad-23 hov1 s-text2">Search</button>
				    </div>
				</div>
			</div>
			</form>
		</div>
	</div>
</section>
<!-- New Restaurants -->
<div class="banner bgwhite p-t-10 p-b-20">
	<div class="container">
		<div class="sec-title p-b-22">
			<h3 class="m-text5 t-center">New Restaurants</h3>
		</div>
		<div class="row">
		    <?php foreach($this->restaurants as $restaurant):?>
			<div class="col-sm-10 col-md-8 col-lg-4 m-l-r-auto">
				<?php echo $restaurant['restaurant_name'];?>
				<div class="block1 hov-img-zoom pos-relative m-b-30">
				    <a href="<?php echo $this->getBaseURL()."/restaurant/".$restaurant['restaurant_id']; ?>">
					    <img src="<?php echo $this->getAssetsURL().'/images/restaurants/'.$restaurant['image']; ?>" alt="IMG-BENNER">
					</a>
				</div>
			</div>
			<?php endforeach ?>
		</div>
	</div>
</div>
<!-- Mapbox -->
<style>
	#map { 
	    width: 0px;
	}
	.geocoder {
    	width: 100%;
    }
    .mapboxgl-ctrl-geocoder {
        min-width: 100%;
    }

</style>
<script>
    mapboxgl.accessToken = 'pk.eyJ1IjoiZ2xhZHlzYnJvY2UiLCJhIjoiY2s4dm12a3d3MGpjNjNqbzd1NDVnN3NkeCJ9.6MLAKKbn0ssuw6JtUT9DKA';
	var lng, lat;
    if ("geolocation" in navigator){  // Get current location
        navigator.geolocation.getCurrentPosition(getPosition,setDefPosition,{timeout:10000});
    }
	/* Set current location if geolocation is available */
	function getPosition(position){
		$("#longitude").attr("value", position.coords.longitude);
		$("#latitude").attr("value", position.coords.latitude);
	}
	/* Set default location to Manila if geolocation is not available */
	function setDefPosition(){
		$("#longitude").attr("value", 121.000000);
		$("#latitude").attr("value", 14.583330);
	}
	var map = new mapboxgl.Map({
       container: 'map',
       style: 'mapbox://styles/mapbox/streets-v11',
       center: [121.000000, 14.583330], // Default: Manila
       zoom: 13
    });
    var geocoder = new MapboxGeocoder({
        accessToken: mapboxgl.accessToken,
        mapboxgl: mapboxgl
    });
    document.getElementById('geocoder').appendChild(geocoder.onAdd(map));
	geocoder.on('result', function(data) {
		$("#address").attr("value", data["result"]["place_name"]);
		$("#longitude").attr("value", data["result"]["center"][0]);
		$("#latitude").attr("value", data["result"]["center"][1]);
	});
</script>